services:
  - type: web
    name: notepad
    env: static
    rootDir: notepad
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
