services:
  - type: web
    name: notepad
    env: node
    plan: free
    rootDir: notepad
    buildCommand: npm install --omit=dev
    startCommand: npm start
    pullRequestPreviewsEnabled: false
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
