services:
  - type: web
    name: notepad
    env: node
    rootDir: notepad
    buildCommand: ""
    startCommand: node server.js
    pullRequestPreviewsEnabled: false
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
